### ISSUE TITLE
Not able to use vim keybindings which were there before upgrading VSpaceCode

### ISSUE THREAD

**Issue by lalitmee** [VSpaceCode/VSpaceCode#90] opened 2020-08-23 09:54 UTC
I am facing this issue after updating to the new VSpaceCode which shows the which-key menu in the vscode. There were some keybinding like `easymotion` keybindings and some of my custom keybindings which I defined in the user settings of vscode. I am not able to use them now.

### Configuration

```json
  "vim.leader": "<Space>",
  "vim.easymotion": true,
  "vim.easymotionMarkerFontWeight": "600",
  "vim.easymotionMarkerForegroundColorOneChar": "yellow",
  "vim.easymotionMarkerForegroundColorTwoChar": "yellow",
  "vim.sneak": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.statusBarColorControl": false,
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "commands": ["workbench.action.files.saveAll"],
      "before": [" ", ","]
    },
    {
      "commands": ["workbench.action.closeAllEditors"],
      "before": ["<C-w>", "k"]
    },
    {
      "commands": ["workbench.action.reopenClosedEditor"],
      "before": [" ", "u"]
    },
    {
      "commands": ["workbench.action.toggleSidebarVisibility"],
      "before": [" ", "b", "c"]
    },
    {
      "commands": ["editor.action.selectHighlights"],
      "before": [" ", "a"]
    },
    {
      "commands": ["editor.action.addSelectionToNextFindMatch"],
      "before": [" ", "n"]
    },
    {
      "before": ["<C-h>"],
      "after": ["<C-w>", "h"]
    },
    {
      "before": ["<C-k>"],
      "after": ["<C-w>", "k"]
    },
    {
      "before": ["<C-j>"],
      "after": ["<C-w>", "j"]
    },
    {
      "before": ["<C-l>"],
      "after": ["<C-w>", "l"]
    },
    {
      "before": ["<space>"],
      "commands": ["vspacecode.space"]
    }
  ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [">"],
      "commands": ["editor.action.indentLines"]
    },
    {
      "before": ["<"],
      "commands": ["editor.action.outdentLines"]
    },
    {
      "before": ["<space>"],
      "commands": ["vspacecode.space"]
    }
  ],
  "vim.enableNeovim": true,
  "vim.neovimPath": "/home/linuxbrew/.linuxbrew/bin/nvim",
  "vim.visualModeKeyBindings": [
    {
      "before": ["<leader>", "<space>"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.showCommands",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", ";", ";"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.commentLine",
          "args": []
        }
      ]
    },
    {
      "before": ["f", "d"],
      "after": ["<Esc>"]
    },
    {
      "before": ["<leader>", "j", "="],
      "after": [],
      "commands": [
        {
          "command": "editor.action.format",
          "args": []
        }
      ]
    }
  ],
  "vim.normalModeKeyBindings": [
    {
      "before": ["<leader>", "<space>"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.showCommands",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "<tab>"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.openNextRecentlyUsedEditorInGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", ";", ";"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.commentLine",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "'"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.terminal.toggleTerminal",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "/"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.findInFiles",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "1"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusFirstEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "2"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusSecondEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "3"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusThirdEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "4"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusFourthEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "5"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusFifthEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "6"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusSixthEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "7"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusSeventhEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "8"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusEighthEditorGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "b", "b"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.showAllEditors",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "b", "d"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.closeActiveEditor",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "b", "n"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.nextEditor",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "b", "p"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.previousEditor",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "b", "s"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.newUntitledFile",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "e", "l"],
      "after": [],
      "commands": [
        {
          "command": "workbench.actions.view.problems",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "e", "n"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.marker.next",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "e", "p"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.marker.prev",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "f", "e"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.openGlobalSettings",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "f", "f"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.openFile",
          "args": [],
          "when": "!isMac"
        },
        {
          "command": "workbench.action.files.openFileFolder",
          "args": [],
          "when": "isMac"
        }
      ]
    },
    {
      "before": ["<leader>", "f", "r"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.openRecent",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "f", "s"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.saveAll",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "f", "t"],
      "after": [],
      "commands": [
        {
          "command": "workbench.view.explorer",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "f", "y"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.copyPathOfActiveFile",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "b"],
      "after": [],
      "commands": [
        {
          "command": "git.checkout",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "c"],
      "after": [],
      "commands": [
        {
          "command": "git.commit",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "d"],
      "after": [],
      "commands": [
        {
          "command": "git.deleteBranch",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "f"],
      "after": [],
      "commands": [
        {
          "command": "git.fetch",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "i"],
      "after": [],
      "commands": [
        {
          "command": "git.init",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "m"],
      "after": [],
      "commands": [
        {
          "command": "git.merge",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "p"],
      "after": [],
      "commands": [
        {
          "command": "git.publish",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "s"],
      "after": [],
      "commands": [
        {
          "command": "workbench.view.scm",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "S"],
      "after": [],
      "commands": [
        {
          "command": "git.stage",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "g", "U"],
      "after": [],
      "commands": [
        {
          "command": "git.unstage",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "h", "d"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.openGlobalKeybindings",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "i", "s"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.insertSnippet",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "j", "="],
      "after": [],
      "commands": [
        {
          "command": "editor.action.formatDocument",
          "args": []
        }
      ]
    },
    {
      "before": ["leader", "j", "j"],
      "after": ["leader", "leader", "s"]
    },
    {
      "before": ["leader", "j", "l"],
      "after": ["leader", "leader", "leader", "b", "d", "j", "k"]
    },
    {
      "before": ["leader", "j", "w"],
      "after": ["leader", "leader", "leader", "b", "d", "w"]
    },
    {
      "before": ["<leader>", "l", "d"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.closeFolder",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "p", "f"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.quickOpen",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "p", "l"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.openFolder",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "p", "p"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.openRecent",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "p", "t"],
      "after": [],
      "commands": [
        {
          "command": "workbench.view.explorer",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "q", "f"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.closeWindow",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "q", "q"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.closeWindow",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "q", "r"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.reloadWindow",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "r", "s"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.findInFiles",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "s", "e"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.rename",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "s", "j"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.gotoSymbol",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "s", "p"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.findInFiles",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "s", "P"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.findInFilesWithSelectedText",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "T", "F"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.toggleFullScreen",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "T", "m"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.toggleMenuBar",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "T", "s"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.selectTheme",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "T", "t"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.toggleActivityBarVisibility",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "v"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.smartSelect.grow",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "V"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.smartSelect.shrink",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "-"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.splitEditorDown",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "/"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.splitEditorRight",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "d"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.closeEditorsInGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "h"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusPreviousGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "H"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.moveActiveEditorGroupLeft",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "j"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusBelowGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "k"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusAboveGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "l"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusNextGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "L"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.moveActiveEditorGroupRight",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "m"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.maximizeEditor",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "v"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.splitEditor",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "w"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusNextGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "w", "W"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.focusPreviousGroup",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "x", "s"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.sortLinesAscending",
          "args": []
        }
      ]
    },
    {
      "before": ["<leader>", "x", "w"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.trimTrailingWhitespace",
          "args": []
        }
      ]
    }
  ],
  "vim.insertModeKeyBindings": [
    {
      "before": ["f", "d"],
      "after": ["<Esc>"]
    }
  ],
```

Any help?

**Comment by stevenguh** [comment] 2020-08-23 16:59
The old vim keybindings are not compatible with the extension. You will have to remove the the leader key and bindings related to the leader key.

The extension bundles a default binding, you can migrate your custom bindings [incrementally](https://github.com/VSpaceCode/VSpaceCode#incrementally) or [from scratch](https://github.com/VSpaceCode/VSpaceCode#from-scratch)

**Comment by lalitmee** [comment] 2020-08-27 13:20
@stevenguh , I selected to merge my settings while installing the extension. So now I am not understanding why some of my keybindings are not working like `easymotion` keybindings are not working. Don't know why. 

By migrate you mean that I can add those keybindings like default keybindings?

**Comment by MarcoIeni** [comment] 2020-08-27 18:04
> I selected to merge my settings while installing the extension

This process doesn't convert old key bindings syntax to new one.

The old syntax is not usable anymore if you want to install this extension from the marketplace and enjoy which-key functionalities. If you don't need this nice new stuff and you want to keep your configuration see the branch [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim).

If you want to migrate to new functionalities see [this](https://github.com/VSpaceCode/VSpaceCode#menu-customization) section of the README.

My advice:
A lot of your settings are now default, so if you installed the extension from the marketplace, comment all your settings and remove comments incrementally based on the things you miss :)

**Comment by lalitmee** [comment] 2020-08-30 10:24
@MarcoIeni, I got you. But I think there is a bug in the keybinding because the new extension which I installed is having the keybindings to jump to words and lines but when I perform the keybinding, it's doing something else instead of jumping to words or lines. **For example**: `jump to a word` is deleting the last word of the line and `jump to a line` is deleting the whole line on which I am currently.

What to do in this case? Am I the only one facing this issue or someone else is also has reported the issue? I didn't see any issue related to this.

I wonder if this functionality is there in this new extension.

**Comment by MarcoIeni** [comment] 2020-08-30 10:33
I am not able to reproduce this issue in my setup.

So please, if the issue of the title is solved now you should close this issue and open a new one where you describe the new problem.

Please, include your `settings.json` in the bug report, too.

Thanks

**Closed** 2020-09-01 08:23 UTC

**Comment by danielo515** [comment] 2020-09-17 12:14
So, this plugin is supposed to ve a super-set of VSCodeVim keybindings, but I don't see a way to do things that were possible with the VSCodeVim. For example, imagine I want to insert a whiteline above the cursor:

```
    {
      "before": [" ", "k"],
      "after": ["O", "<Esc>"]
    },
```

How can I do that with this extension ?

**Comment by danielo515** [comment] 2020-09-17 12:21
By the way, a possible workaround is to hide the vspacecode bindinb behind a double leader key or a different leader key:

```
    {
      "before": ["<space>", "<space>"],
      "commands": ["vspacecode.space"]
    }
```

**Comment by stevenguh** [comment] 2020-09-17 17:10
> So, this plugin is supposed to ve a super-set of VSCodeVim keybindings, but I don't see a way to do things that were possible with the VSCodeVim. For example, imagine I want to insert a whiteline above the cursor:
> 
> ```
>     {
>       "before": [" ", "k"],
>       "after": ["O", "<Esc>"]
>     },
> ```
> 
> How can I do that with this extension ?

You should be able do this with an override
```json
{
  "vspacecode.bindingOverrides": [
    {
      "keys": "k",
      "name": "New line above",
      "type": "command",
      "command": "vim.remap",
      "args": {
        "after": [
          "O",
          "<esc>",
        ]
      }
    }
  ]
}
```

**Comment by danielo515** [comment] 2020-09-18 12:01
Ok, that  command `vim.remap` and the  `args` property is what I was missing. Is it documented anywhere?

**Comment by MarcoIeni** [comment] 2020-09-18 17:44
No, if you want to do a PR where you provide an example you are welcome :)
[This](https://github.com/VSpaceCode/vspacecode.github.io/blob/master/docs/menu-customization.md) should be the appropriate place I think.

**Comment by stevenguh** [comment] 2020-09-18 17:58
Opened an issue https://github.com/VSpaceCode/vspacecode.github.io/issues/3

**Comment by danielo515** [comment] 2020-10-07 10:31
If anyone is interested, I just wrote this silly script to convert from VsCode space mappings to this plugin ones:

```js
const createMapping = ({ before: [space, ...rest], after, commands }) => ({
  keys: rest,
  name: "change-me",
  type: "command",
  command: commands || "vim.remap",
  ...(after && {
    args: { after },
  }),
});

// This are just normal mode ones. Put your entire list here, we filter by space prefix
const existing = [
  {
    before: ["s"],
    after: [" ", " ", "/"],
  },
  {
    before: [" ", "t", "s"],
    after: ["y", "s", "a", "<"],
  },
  {
    before: ["g", "r"],
    after: ["c", "i", "w", "<C-r>", "0", "<Esc>"],
  },
  {
    before: [" ", "s"],
    after: [" ", " ", "w"],
  },
  {
    before: [" ", "f"],
    commands: ["editor.action.formatDocument"],
  },
];

const result = {
  "vspacecode.bindingOverrides": existing
    .filter(({ before: [prefix] }) => prefix === " ")
    .map(createMapping),
};
console.log(JSON.stringify(result, null, 2));
```
