### ISSUE TITLE
<leader> f f  broken? 

### ISSUE THREAD

**Issue by JuanCaicedo** [VSpaceCode/VSpaceCode#6] opened 2017-12-31 02:14 UTC
I'm finding that if I press `<leader> f f `, nothing happens. More concerning, it also stops other bindings like `<leader> <leader>` from working correctly until I close that editor and open a new one. 

Any idea why this might be happening? I'm not sure if it's a bug here or in VSCodeVim

**Comment by StreakyCobra** [comment] 2018-01-02 11:20
Hi,

I don't have this problem on the latest version of VSCode and VSCodeVim, neither on Windows nor on Linux, so I don't really now how to help you :-/

This repository only provides a configuration of VSCodeVim that makes it to behave like Spacemacs, so you may try to reduce your own configuration file to a minimal state that allow to reproduce the problem, to see if maybe the problem is coming from some other configuration/extensions that you may have.

**Comment by rosingle** [comment] 2018-01-12 02:13
use workbench.action.files.openFileFolder on Mac

**Comment by JuanCaicedo** [comment] 2018-01-15 07:40
@rosingle's solution fixes this for me (on mac)! Does it work on Windows and Linux @StreakyCobra ? If so, maybe the command can be switched. If not, not sure how/if you think this could be handled. Maybe just a note in the documentation? I can make a PR for it

**Comment by StreakyCobra** [comment] 2018-01-15 08:13
@JuanCaicedo The quick test I made on Windows doesn't seem to work. I'll test on Linux later. I thought about setting the shortcut differently regarding the operating system in use, but this doesn't seem to be possible currently (https://github.com/Microsoft/vscode/issues/8962).

The only option I see for now is to put a note in the README for OS X users. Other ideas?

**Comment by JuanCaicedo** [comment] 2018-01-16 07:43
Note in the readme seems like a fine solution to me!

**Comment by StreakyCobra** [comment] 2018-01-17 09:11
This issue has been fixed by f1cb0bf8e58c1a24146f6f1d9ce9392a23243af2 and 90c87df8337619a8fd79d4f37c3022aa329f534d

**Closed by StreakyCobra** 2018-01-17 09:11 UTC
