### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by gargolito** [VSpaceCode/VSpaceCode#219] opened 2021-08-06 22:03 UTC
## Expected behavior

It uninstalls

## Error Messages:

Cannot uninstall 'VSpaceCode' extension . It includes uninstalling 'Which Key' extension and 'VSpaceCode' extension depends on this.

Cannot uninstall 'Which Key' extension. 'VSpaceCode' extension depends on this.
</p>
</details>

## System information

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.05GB free)
Process Argv | --crash-reporter-id 8d05d8a5-44df-4c34-a34b-fc55ad647400
Screen Reader | no
VM | 0%

rainbow-brackets | 2gu | 0.0.6
better-comments | aar | 2.1.0
Bookmarks | ale | 13.1.0
stackoverflow-search | Ale | 1.2.0
clara-copilot | Bad | 0.0.3
file-browser | bod | 0.2.10
vscode-markdownlint | Dav | 0.43.2
py-pack | dav | 1.2.0
vscode-eslint | dba | 2.1.23
gitlens | eam | 11.6.0
prettier-vscode | esb | 8.1.0
code-runner | for | 0.11.5
pythonsnippets | frh | 1.0.2
vscode-test-explorer | hbe | 2.20.4
rest-client | hum | 0.24.5
workspacesort | ici | 1.6.1
fuzzy-search | jac | 0.0.3
firebase-explorer | jsa | 0.3.3
magit | kah | 0.6.18
google-search | kam | 0.0.1
vscode-jest-test-adapter | kav | 0.8.1
vsc-python-indent | Kev | 1.14.2
vscode-python-test-adapter | lit | 0.7.0
vscode-docker | ms- | 1.15.0
vscode-kubernetes-tools | ms- | 1.3.3
python | ms- | 2021.8.1105858891
vscode-pylance | ms- | 2021.8.0
jupyter | ms- | 2021.8.1195043623
remote-containers | ms- | 0.191.0
remote-ssh | ms- | 0.65.7
remote-ssh-edit | ms- | 0.65.7
vscode-remote-extensionpack | ms- | 0.21.0
hexeditor | ms- | 1.8.2
test-adapter-converter | ms- | 0.1.2
reload | nat | 0.0.6
autodocstring | njp | 0.5.4
fix-json | oli | 0.1.2
material-icon-theme | PKi | 4.9.0
tsimporter | pmn | 2.0.1
vscode-yaml | red | 0.22.0
trailing-spaces | sha | 0.3.1
vsc-workspace-sidebar | ske | 1.2.8
splunk | Spl | 0.2.6
code-spell-checker | str | 1.10.2
shellcheck | tim | 0.15.2
vim | vsc | 1.21.5
gistfs | vsl | 0.3.0
vspacecode | VSp | 0.10.1
whichkey | VSp | 0.9.2
snippets-explorer | wwa | 1.0.5
local-history | xyz | 1.8.1
markdown-all-in-one | yzh | 3.4.0
html-css-class-completion | Zig | 1.20.0

**Comment by MarcoIeni** [comment] 2021-08-06 22:17
I was able to reproduce this, I am sorry for the inconvenience. Maybe it is due to the new VSCode update.
As a workaround maybe you can try deleting the extension from the filesystem, like explained [here](https://stackoverflow.com/questions/36746857/completely-uninstall-vs-code-extensions) but I have not tested this.

**Comment by MarcoIeni** [comment] 2021-08-06 22:45
I reproduced on vscode 1.59. Is somebody able to reproduce this on vscode 1.58?
@stevenguh do you think we have changed something that raised this bug or should we open an issue upstream?

**Comment by MarcoIeni** [comment] 2021-08-06 23:04
I have prepared a bug report in case you confirm that you don't think it's our fault:


- VS Code Version: 1.59 and insiders build 
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. Install extension `vspacecode.whichkey`
2. Install extension `vspacecode.vspacecode`
3. Try to uninstall vspacecode

I get the following error:
![image](https://user-images.githubusercontent.com/74915166/128578579-77f74701-e3a0-44b2-9974-eaac4da49e9d.png)

This doesn't make sense, because it is saying that I cannot uninstall extension A because it depends on extension B. But extension B is the extension I am trying to uninstall.

**Comment by stevenguh** [comment] 2021-08-07 00:32
Just tested. VSpaceCode can be uninstalled in 1.58, and can't in 1.59.

Thanks for getting a report ready. @MarcoIeni Can you filed the issue on vscode github?

**Comment by MarcoIeni** [comment] 2021-08-07 11:41
FYI Steven has submitted a PR to fix this issue upstream: https://github.com/microsoft/vscode/pull/130317
Thanks 🙏

**Comment by stevenguh** [comment] 2021-08-18 03:05
Closing this as the fix is merged upstream and will be released on the next stable release.

🧵The workaround for now is mentioned in https://github.com/microsoft/vscode/issues/130310#issuecomment-900144751:

 > Here is a workaround for now to use in stable - To uninstall open extensions folder using command Extensions: Open Extensions Folder and remove the extension.

**Closed by stevenguh** 2021-08-18 03:05 UTC
Labels: bug, upstream

**Comment by MarcoIeni** [comment] 2021-09-06 19:29
Hey @gargolito with VSCode 1.60 this extension can be uninstalled correctly.
Do you mind updating or removing your review [here](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode) since this issue was not caused by us, but it was an upstream problem? Thanks :)

**Comment by gargolito** [comment] 2021-09-07 19:02
> Hey @gargolito with VSCode 1.60 this extension can be uninstalled correctly.
> Do you mind updating or removing your review [here](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode) since this issue was not caused by us, but it was an upstream problem? Thanks :)

done
