### ISSUE TITLE
Visual mode after `<` shift indentation should not exit selection?

### ISSUE THREAD

**Issue by concretevitamin** [VSpaceCode/VSpaceCode#317] opened 2023-04-28 00:12 UTC
## To Reproduce
Under visual mode, I press `<` to shift indentation of the code selected. However, this then exits the editor out of the selection. Namely, I can't select some text and hit multiple `< <` to shift multiple times. 

This seems inconsistent with Spacemacs behavior? Maybe I'm missing some setting. Thanks.

## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
// Copy paste the content of your keybindings.json file here.
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
// Copy paste the content of your settings.json file here.
```

</p>
</details>

**Comment by MarcoIeni** [comment] 2023-04-28 06:46
This is an issue with https://github.com/VSCodeVim/Vim
I was able to reproduce this issue with Vim enabled and VSpaceCode disabled.

**Comment by concretevitamin** [comment] 2023-04-29 05:23
@MarcoIeni I should clarify that in regular Vim after a `>` you do exit selection so the second `>` won't apply to the previous selection.

However, the issue was about inconsistency with Spacemacs behavior. After I selected some text I can see the key is bound to:
```
> runs the command (lambda nil (interactive) (progn (call-interactively
  'evil-shift-right) (execute-kbd-macro "gv"))) (found in
  evil-visual-state-map), which is an interactive Lisp function.

It is bound to >.
```
With this, multiple `>` works. 

Question is, can VSpaceCode imitate this behavior somehow?

**Comment by MarcoIeni** [comment] 2023-04-29 06:58
VSpaceCode relies on the vim plugin for vscode, which we don't maintain: https://github.com/VSCodeVim/Vim

 this issue should be addressed in their repository I think

**Comment by MarcoIeni** [comment] 2023-04-29 07:27
Oh, this is not the default behavior in vim, I see, sorry 👍

**Comment by Ambrosia** [comment] 2023-04-29 13:34
Using the . key works, it'll still do the indent again even after the selection is lost. This key repeats your last action and works with pretty much anything.

**Comment by concretevitamin** [comment] 2023-04-29 16:43
> Using the `.` key works, it'll still do the indent again even after the selection is lost. This key repeats your last action and works with pretty much anything.

This is a functional workaround, but it'd be great to press `>` multiple times which is more convenient.

**Comment by stevenguh** [comment] 2023-04-30 20:56
Just to recap:
1. `<` or `>` on visual mode will exit out of the mode
2.  Hence, `<` or `>` cannot be perform repeatability
3. This is the same behavior as vim but not spacemacs

There is a workaround documented in https://github.com/microsoft/vscode
> - Bind `>` and `<` in visual mode to indent/outdent lines (repeatable):
>
> ```json
>     "vim.visualModeKeyBindings": [
>         {
>             "before": [
>                 ">"
>             ],
>             "commands": [
>                 "editor.action.indentLines"
>             ]
>         },
>         {
>             "before": [
>                 "<"
>             ],
>             "commands": [
>                 "editor.action.outdentLines"
>             ]
>         },
>     ]
> ```
 
However, it will make `.` not work as expected because this is not using VsCodeVIm to indent.

**Comment by concretevitamin** [comment] 2023-04-30 21:09
@stevenguh Thanks! That works for me. Feel free to keep it open (for the `.` key, which I don't use in this case) or closed.

**Comment by stevenguh** [comment] 2023-04-30 21:26
@MarcoIeni Any thoughts? Should we put the workaround in https://github.com/VSpaceCode/VSpaceCode/blob/master/src/configuration/settings.jsonc?

**Comment by MarcoIeni** [comment] 2023-05-01 08:39
yes 🎉

**Closed** 2023-07-20 03:14 UTC
Labels: bug
