### ISSUE TITLE
<spc 0> "Focus on Files Explorer" does not work if current file is not from the open folder

### ISSUE THREAD

**Issue by evaera** [VSpaceCode/VSpaceCode#175] opened 2021-02-16 06:43 UTC
## Bug description

The "Focus on Files Explorer" binding doesn't work if the file you have open isn't from the folder you have open, for example VSCode's `settings.json` or any other file that's outside of your active folder.

## To Reproduce

1. Open a file outside of your workspace root
2. Press <kbd>SPC</kbd> <kbd>0</kbd>
3. It does not do anything

## Expected behavior

Explorer should still be focused, even if it can't select the active file

## System information

<details>

CPUs | Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 63.84GB (39.23GB free)
Process Argv | --crash-reporter-id 1cb26fec-24db-4f09-b172-b95c70dc100a
Screen Reader | no
VM | 18%

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.1.0
Bookmarks | ale | 13.0.1
project-manager | ale | 12.0.1
vscode-database | baj | 2.2.3
file-browser | bod | 0.2.10
vscode-toggle-quotes | Bri | 0.3.4
better-toml | bun | 0.3.2
npm-intellisense | chr | 1.3.1
path-intellisense | chr | 2.3.0
bracket-pair-colorizer | Coe | 1.0.61
vscode-eslint | dba | 2.1.14
githistory | don | 0.6.14
gitlens | eam | 11.2.1
EditorConfig | Edi | 0.16.4
vsc-material-theme | Equ | 30.0.0
prettier-vscode | esb | 5.9.2
roblox-api-explorer | eva | 1.1.0
vscode-rojo | eva | 1.12.5
vscode-codeql | Git | 1.4.2
vscode-pull-request-github | Git | 0.23.0
go | gol | 0.22.1
gc-excelviewer | Gra | 3.0.41
todo-tree | Gru | 0.0.196
vscode-test-explorer | hbe | 2.19.5
vscode-drawio | hed | 1.3.0
svgeditor | hen | 2.9.0
beautify | Hoo | 1.5.0
vue-autoimport | ish | 1.0.5
fuzzy-search | jac | 0.0.3
docthis | joe | 0.7.1
stylua | Joh | 1.0.3
vscode-styled-components | jpo | 1.5.0
roblox-lua-autofills | Kam | 1.7.1
selene-vscode | Kam | 1.0.3
vscode-gutter-preview | kis | 0.26.2
nim | kos | 0.6.6
node-module-intellisense | lei | 1.5.0
rust-analyzer | mat | 0.2.489
dotenv | mik | 1.0.1
vs-deploy | mkl | 14.0.0
vscode-json5 | mrm | 1.0.0
vscode-docker | ms- | 1.9.1
csharp | ms- | 1.23.9
vscode-kubernetes-tools | ms- | 1.3.0
python | ms- | 2021.1.502429796
jupyter | ms- | 2020.12.414227025
remote-containers | ms- | 0.158.0
remote-ssh | ms- | 0.64.0
remote-ssh-edit | ms- | 0.64.0
remote-wsl | ms- | 0.53.4
vscode-remote-extensionpack | ms- | 0.20.0
cpptools | ms- | 1.2.0
hexeditor | ms- | 1.4.0
sublime-keybindings | ms- | 4.0.7
vscode-typescript-tslint-plugin | ms- | 1.3.3
vsliveshare | ms- | 1.0.3629
debugger-for-chrome | msj | 4.12.12
vshaxe | nad | 2.22.0
language-liquid | nei | 0.1.1
robloxlsp | Nig | 0.15.6
vetur | oct | 0.32.0
indent-rainbow | ode | 7.5.0
material-icon-theme | PKi | 4.5.0
quicktype | qui | 12.0.46
vscode-yaml | red | 0.15.0
synthwave-vscode | Rob | 0.1.8
code-settings-sync | Sha | 3.4.3
mdx | sil | 0.1.0
vscode-quick-scope | ska | 0.2.0
shader | sle | 1.1.5
vscode-autohotkey | sle | 0.2.2
addDocComments | ste | 0.0.8
rewrap | stk | 1.14.0
code-spell-checker | str | 1.10.2
vscode-rust-test-adapter | Swe | 0.11.0
language-stylus | sys | 1.11.0
vsfire | tob | 1.4.1
shell-launcher | Tyr | 0.4.1
roblox-lua | Und | 1.0.4
errorlens | use | 3.2.4
vim | vsc | 1.18.9
vspacecode | VSp | 0.9.0
whichkey | VSp | 0.8.4
markdown-all-in-one | yzh | 3.4.0
material-theme | zhu | 3.9.13

</details>

**Comment by stevenguh** [comment] 2021-02-17 03:42
I am not able to reproduce this with both windows and mac. In steps two, did you mean <kbd>SPC</kbd> <kbd>0</kbd>?

**Comment by evaera** [comment] 2021-02-17 05:16
> I am not able to reproduce this with both windows and mac. In steps two, did you mean SPC 0?

Yes, looks like GitHub ate the `<space>` in my comment: 
![image](https://user-images.githubusercontent.com/2489210/108159626-6755cd80-70b5-11eb-9cca-0ed9f435b74e.png)

**Comment by stevenguh** [comment] 2021-02-17 05:27
Ah, that was treated as HTML tag. I think I might have figure out what's the bug your mean.

When triggering <kbd>SPC</kbd> <kbd>0</kbd> in a buffer of a file outside of the workspace, it focused on the "open editor" area of the explore instead of the workspace folder.

Instead of like how <kbd>SPC</kbd> <kbd>f</kbd> <kbd>t</kbd> works, it always focuses on the workspace folder.

Context of this command: https://github.com/VSpaceCode/VSpaceCode/issues/138#issuecomment-740801064
Maybe we can change the command of <kbd>SPC</kbd> <kbd>0</kbd> @lawrsp

**Comment by evaera** [comment] 2021-02-17 05:39
Yeah. <kbd>SPC</kbd> <kbd>f</kbd> <kbd>t</kbd> closes the explorer pane for me, though... so that's not what I want either. 

I just want to focus it, like with: `workbench.files.action.focusFilesExplorer`

**Comment by stevenguh** [comment] 2021-02-17 07:32
> but they are not duplicated, one is for toggle (same as workbench.view.explorer), and the other is to open (same as workbench.files.action.showActiveFileInExplorer)

I think the original intent was to have
- <kbd>SPC</kbd> <kbd>f</kbd> <kbd>t</kbd> to toggle file explorer (show/hide and side bar)
- <kbd>SPC</kbd> <kbd>0</kbd> to focus on file explorer

However, `workbench.files.action.showActiveFileInExplorer` will focus to "open editor" area if the file is not in the workspace. `workbench.files.action.focusFilesExplorer` seems to be a better command in which it will always focus on the workspace (folders) area, and consistent with spacemacs' `treemacs-select`.

For the  curious, `workbench.view.explorer` is toggling focus between the Explorer sidebar and the main buffer window.

**Comment by stevenguh** [comment] 2021-02-20 06:18
@evaera Do you wanna submit PR for this?

**Comment by lawrsp** [comment] 2021-04-24 09:06
sorry, just saw this @stevenguh @evaera 

I think the best action is to open the project folder where the file located then focus on it.
This seems complicated...

`workbench.files.action.focusFilesExplorer` also has a shorcoming: 
if the folder is folded, it don't unfold it, but `showActiveFileInExplorer` could do it.

however, `focusFilesExplorer` is better then `showActiveFileInExplorer` in general use, I will make PR to change it

**Comment by stevenguh** [comment] 2021-05-01 00:37
@lawrsp Thanks for contributing. Merged :)

**Closed** 2021-05-01 00:36 UTC
Labels: bug
